### ISSUE TITLE
Move appendix A of the I-D into a new I-D submitteed to Netmod WG

### ISSUE THREAD

**Issue by italobusi** [danielkinguk/transport-nbi#39]
There was some offline interest shown during IETF 102 for having the JSON code examples validation tools shared to broader community

It would be therefore worthwhile taking the material in Appendix A of the Applicability Statement I-D and move it into a new I-D to be submitted to Netmod WG

- [ ] Pending resolution of open issue #54 
- [ ] Pending actions from DT call on January 16, 2019: https://github.com/danielkinguk/transport-nbi/issues/39#issuecomment-454833233

Keep the Appendix A and use it as an input for a new Netmod WG I-D:
https://github.com/danielkinguk/transport-nbi/blob/master/Meetings/2019-03-23-29-IETF104/minutes-transport-nbi-dt-2019-03-27-ietf104.md

**Comment by italobusi** [comment]
May depend also on the resolution of open issue #54

**Comment by italobusi** [comment]
Discussed during the DT call on January 16, 2019:

https://github.com/danielkinguk/transport-nbi/tree/master/Meetings/2019-01-16

**Actions (Italo):**
- [ ] Check with Benoit. See also: https://github.com/danielkinguk/transport-nbi/issues/54#issuecomment-454832127

**Comment by danielkinguk** [comment]
No longer planning to do this.
